name = input("Enter your full name:")

# result = (len(name))
# result = name.find("u")
# result = name.rfind("a")
# result = name.capitalize()
# result = name.upper()
# result = name.lower()
# result = name.isdigit()
# result = name.isalpha()
# result = name.count("p")
# result = name.replace("p","t")
print(help(str))

# print(result)